#!/usr/bin/env python3
"""
quantize_model.py

INT8 post-training quantization of SPARK's Layer-2 1D CNN for TFLite
Micro deployment on ESP32-S3.

Takes the trained Keras model from train_cnn.py and produces:
    1. spark_cnn_int8.tflite  — fully INT8 quantized FlatBuffer
    2. spark_cnn_int8.h        — C header byte array for firmware #include
    3. quantization_report.txt — size, tensor details, FP32-vs-INT8 metrics

Quantization recipe per proposal §5 (methodology, verbatim):
    Post-training INT8 quantization via TFLite Converter with a
    representative calibration dataset (200 randomly sampled training
    windows). Exported as a C byte array using xxd -i equivalent.
    Model size target: ≤ 120 KB flash.

Evaluation (proposal §5, verbatim): Results are reported for both the
FP32 Keras model and the INT8 TFLite Micro model to quantify
quantization accuracy loss. Same 4 metrics as train_cnn.py: Sensitivity,
Specificity, F1, AUC-ROC.

Firmware integration note: the .tflite has fully INT8 input/output
tensors. The firmware's inference.h float32 API boundary handles
dequantization as an implementation detail (documented in inference.h
comments), so callers never see int8 directly.

Usage:
    python quantize_model.py --data /path/to/output_dir

Where <data> contains windows.npy, labels.npy, meta.csv, and
model/spark_cnn.keras as produced by prepare_sisfall.py + train_cnn.py.

Optional:
    --firmware-out /path/to/firmware/main/models
        Also copies spark_cnn_int8.h to the given firmware directory
        for direct #include integration.

    --num-calibration 200
        Number of training windows for representative dataset (default
        200, matching the proposal spec).
"""

import argparse
import csv
import shutil
import sys
import textwrap
from pathlib import Path

import numpy as np
import tensorflow as tf
from sklearn.metrics import f1_score, roc_auc_score
from sklearn.model_selection import GroupShuffleSplit

# Match train_cnn.py's split parameters exactly so we reconstruct the
# same train/test split for metrics comparison.
RANDOM_SEED = 42
TRAIN_FRAC = 0.8
VAL_FRAC = 0.1
NUM_CALIBRATION_WINDOWS = 200

# C header template -- equivalent of `xxd -i` output but with a
# controlled array name and proper include guards.
C_HEADER_TEMPLATE = textwrap.dedent("""\
    // Auto-generated by quantize_model.py — do not edit manually.
    // INT8 quantized SPARK 1D CNN for TFLite Micro on ESP32-S3.
    // Model size: {size_bytes} bytes

    #pragma once

    #include <cstddef>

    alignas(16) const unsigned char spark_cnn_model[] = {{
    {hex_lines}
    }};

    const size_t spark_cnn_model_len = {size_bytes};
""")


def load_data(data_dir: Path):
    """Load windows, binary labels, and subjects — mirrors train_cnn.py's
    load_data() to guarantee the same label encoding."""
    windows = np.load(data_dir / "windows.npy")
    labels_raw = np.load(data_dir / "labels.npy")

    with open(data_dir / "meta.csv") as fh:
        meta_rows = list(csv.DictReader(fh))
    subjects = np.array([r["subject"] for r in meta_rows])

    if len(subjects) != windows.shape[0]:
        raise ValueError(
            f"meta.csv row count ({len(subjects)}) doesn't match "
            f"windows.npy ({windows.shape[0]}) — files out of sync, "
            f"re-run prepare_sisfall.py"
        )

    labels_bin = np.where(np.char.startswith(labels_raw, "F"), 1, 0).astype(np.int32)
    return windows, labels_bin, subjects


def reconstruct_splits(subjects: np.ndarray, labels: np.ndarray, seed: int):
    """Reconstruct the same 80/10/10 grouped-by-subject split that
    train_cnn.py used, so we evaluate on the identical test set."""
    gss1 = GroupShuffleSplit(n_splits=1, train_size=TRAIN_FRAC, random_state=seed)
    trainval_idx, test_idx = next(gss1.split(subjects, labels, groups=subjects))

    val_frac_of_remaining = VAL_FRAC / (TRAIN_FRAC + VAL_FRAC) if (TRAIN_FRAC + VAL_FRAC) else 0
    gss2 = GroupShuffleSplit(n_splits=1, train_size=1 - val_frac_of_remaining, random_state=seed)
    remaining_subjects = subjects[trainval_idx]
    remaining_labels = labels[trainval_idx]
    train_sub_idx, _val_sub_idx = next(
        gss2.split(remaining_subjects, remaining_labels, groups=remaining_subjects)
    )
    train_idx = trainval_idx[train_sub_idx]

    return train_idx, test_idx


def build_representative_dataset(
    windows: np.ndarray, train_idx: np.ndarray, num_samples: int, seed: int
):
    """Returns a generator function for the TFLite Converter's
    representative_dataset parameter. Yields `num_samples` randomly
    sampled training windows as float32 batches of shape (1, 200, 6)."""
    rng = np.random.default_rng(seed)
    chosen = rng.choice(train_idx, size=min(num_samples, len(train_idx)), replace=False)
    calibration_windows = windows[chosen].astype(np.float32)

    def generator():
        for i in range(len(calibration_windows)):
            yield [calibration_windows[i : i + 1]]

    return generator


def quantize_model(
    keras_model_path: Path,
    representative_dataset_fn,
) -> bytes:
    """Apply INT8 post-training quantization to the Keras model.

    Returns the quantized TFLite model as bytes.

    Converter settings:
        - Full integer quantization (all ops INT8)
        - INT8 input and output tensors (firmware handles float↔int8 at
          the API boundary per inference.h contract)
        - Representative dataset for calibration
    """
    model = tf.keras.models.load_model(keras_model_path)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_fn
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    return converter.convert()


def generate_c_header(tflite_bytes: bytes) -> str:
    """Generate a C header file with the model as a byte array, equivalent
    to xxd -i but with controlled naming and alignment."""
    hex_values = [f"0x{b:02x}" for b in tflite_bytes]

    # Format as lines of 12 hex values each (matches xxd -i style)
    lines = []
    for i in range(0, len(hex_values), 12):
        chunk = ", ".join(hex_values[i : i + 12])
        lines.append(f"  {chunk}")
    hex_lines = ",\n".join(lines)

    return C_HEADER_TEMPLATE.format(
        size_bytes=len(tflite_bytes),
        hex_lines=hex_lines,
    )


def evaluate_keras_model(model, X_test: np.ndarray, y_test: np.ndarray) -> dict:
    """Evaluate the FP32 Keras model — same metrics as train_cnn.py."""
    y_prob = model.predict(X_test, verbose=0)
    y_pred = np.argmax(y_prob, axis=1)
    y_prob_fall = y_prob[:, 1]
    return _compute_metrics(y_test, y_pred, y_prob_fall)


def evaluate_tflite_model(tflite_bytes: bytes, X_test: np.ndarray, y_test: np.ndarray) -> dict:
    """Evaluate the INT8 TFLite model using the TFLite interpreter.

    Handles int8 input/output quantization transparently:
    quantize input with (scale, zero_point), dequantize output, then
    compute the same 4 metrics.
    """
    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    # Quantization parameters for input
    input_scale = input_details["quantization"][0]
    input_zero_point = input_details["quantization"][1]

    # Quantization parameters for output
    output_scale = output_details["quantization"][0]
    output_zero_point = output_details["quantization"][1]

    all_probs = []
    for i in range(len(X_test)):
        sample = X_test[i : i + 1].astype(np.float32)

        # Quantize input: int8 = float / scale + zero_point
        if input_details["dtype"] == np.int8:
            sample_q = (sample / input_scale + input_zero_point).astype(np.int8)
        else:
            sample_q = sample

        interpreter.set_tensor(input_details["index"], sample_q)
        interpreter.invoke()
        raw_output = interpreter.get_tensor(output_details["index"])

        # Dequantize output: float = (int8 - zero_point) * scale
        if output_details["dtype"] == np.int8:
            probs = (raw_output.astype(np.float32) - output_zero_point) * output_scale
        else:
            probs = raw_output.astype(np.float32)

        all_probs.append(probs[0])

    all_probs = np.array(all_probs)  # (N, 2)
    y_pred = np.argmax(all_probs, axis=1)
    y_prob_fall = all_probs[:, 1]

    return _compute_metrics(y_test, y_pred, y_prob_fall)


def _compute_metrics(y_true: np.ndarray, y_pred: np.ndarray, y_prob_fall: np.ndarray) -> dict:
    """Shared metric computation: Sensitivity, Specificity, F1, AUC-ROC."""
    fall_mask = y_true == 1
    nonfall_mask = y_true == 0

    sensitivity = (
        (y_pred[fall_mask] == 1).sum() / fall_mask.sum() if fall_mask.sum() else float("nan")
    )
    specificity = (
        (y_pred[nonfall_mask] == 0).sum() / nonfall_mask.sum()
        if nonfall_mask.sum()
        else float("nan")
    )
    f1 = f1_score(y_true, y_pred)
    try:
        auc_roc = roc_auc_score(y_true, y_prob_fall)
    except ValueError as e:
        auc_roc = float("nan")
        print(f"WARNING: AUC-ROC undefined ({e})", file=sys.stderr)

    return {
        "sensitivity": sensitivity,
        "specificity": specificity,
        "f1": f1,
        "auc_roc": auc_roc,
    }


def get_tensor_info(interpreter: tf.lite.Interpreter) -> dict:
    """Extract input/output tensor details for the report."""
    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]
    return {
        "input_shape": input_details["shape"].tolist(),
        "input_dtype": str(input_details["dtype"]),
        "input_quantization": input_details["quantization"],
        "output_shape": output_details["shape"].tolist(),
        "output_dtype": str(output_details["dtype"]),
        "output_quantization": output_details["quantization"],
    }


def format_report(
    tflite_bytes: bytes,
    keras_model_path: Path,
    tensor_info: dict,
    fp32_metrics: dict | None,
    int8_metrics: dict | None,
    num_test_windows: int,
    num_calibration: int,
) -> str:
    """Format the quantization report."""
    keras_size = keras_model_path.stat().st_size
    tflite_size = len(tflite_bytes)
    reduction = (1 - tflite_size / keras_size) * 100 if keras_size > 0 else 0

    lines = [
        "SPARK 1D CNN — INT8 Quantization Report",
        "=" * 50,
        "",
        "Model Files:",
        f"  Keras (FP32):    {keras_model_path.name} ({keras_size:,} bytes)",
        f"  TFLite (INT8):   spark_cnn_int8.tflite ({tflite_size:,} bytes)",
        f"  Size reduction:  {reduction:.1f}%",
        f"  Flash target:    {'✓ PASS' if tflite_size <= 120 * 1024 else '✗ FAIL'}"
        f" (≤ 120 KB, actual {tflite_size / 1024:.1f} KB)",
        "",
        "Quantization Configuration:",
        f"  Calibration windows: {num_calibration}",
        "  Optimization: INT8 full-integer quantization",
        "",
        "Input Tensor:",
        f"  Shape: {tensor_info['input_shape']}",
        f"  Dtype: {tensor_info['input_dtype']}",
        f"  Quantization (scale, zero_point): {tensor_info['input_quantization']}",
        "",
        "Output Tensor:",
        f"  Shape: {tensor_info['output_shape']}",
        f"  Dtype: {tensor_info['output_dtype']}",
        f"  Quantization (scale, zero_point): {tensor_info['output_quantization']}",
    ]

    if fp32_metrics and int8_metrics:
        lines.extend(
            [
                "",
                f"Accuracy Comparison (test set: {num_test_windows} windows):",
                "=" * 50,
                "",
                f"{'Metric':<30} {'FP32':>10} {'INT8':>10} {'Delta':>10}",
                f"{'-' * 30} {'-' * 10} {'-' * 10} {'-' * 10}",
            ]
        )
        for key, label in [
            ("sensitivity", "Sensitivity (Recall, FALL)"),
            ("specificity", "Specificity (Recall, NON_FALL)"),
            ("f1", "F1-score"),
            ("auc_roc", "AUC-ROC"),
        ]:
            fp32_val = fp32_metrics[key]
            int8_val = int8_metrics[key]
            delta = int8_val - fp32_val
            target = " (target >= 0.90)" if key in ("sensitivity", "specificity") else ""
            lines.append(
                f"  {label:<28} {fp32_val:>10.4f} {int8_val:>10.4f} {delta:>+10.4f}{target}"
            )

    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--data",
        required=True,
        type=Path,
        help="Directory containing windows.npy, labels.npy, meta.csv, "
        "and model/spark_cnn.keras from prepare_sisfall.py + train_cnn.py",
    )
    ap.add_argument("--seed", type=int, default=RANDOM_SEED)
    ap.add_argument(
        "--num-calibration",
        type=int,
        default=NUM_CALIBRATION_WINDOWS,
        help="Number of training windows for representative calibration dataset (default: 200)",
    )
    ap.add_argument(
        "--firmware-out",
        type=Path,
        default=None,
        help="Optional path to firmware models directory (e.g. firmware/main/models). "
        "If set, also copies spark_cnn_int8.h there for direct #include.",
    )
    args = ap.parse_args()

    # --- Validate inputs ---
    for required_file in ("windows.npy", "labels.npy", "meta.csv"):
        if not (args.data / required_file).exists():
            print(
                f"ERROR: {required_file} not found in {args.data} — run prepare_sisfall.py first",
                file=sys.stderr,
            )
            sys.exit(1)

    keras_path = args.data / "model" / "spark_cnn.keras"
    if not keras_path.exists():
        print(
            f"ERROR: {keras_path} not found — run train_cnn.py first",
            file=sys.stderr,
        )
        sys.exit(1)

    tf.keras.utils.set_random_seed(args.seed)

    # --- Load data and reconstruct splits ---
    print("Loading data...")
    windows, labels_bin, subjects = load_data(args.data)
    print(f"  {windows.shape[0]} windows, shape {windows.shape[1:]}")

    print("Reconstructing train/test split (must match train_cnn.py)...")
    train_idx, test_idx = reconstruct_splits(subjects, labels_bin, args.seed)
    X_test, y_test = windows[test_idx], labels_bin[test_idx]
    print(f"  train: {len(train_idx)} windows")
    print(f"  test:  {len(test_idx)} windows")

    # --- Build representative dataset ---
    print(f"Building representative calibration dataset ({args.num_calibration} windows)...")
    rep_dataset_fn = build_representative_dataset(
        windows, train_idx, args.num_calibration, args.seed
    )

    # --- Quantize ---
    print("Quantizing model to INT8...")
    tflite_bytes = quantize_model(keras_path, rep_dataset_fn)
    print(
        f"  Quantized model size: {len(tflite_bytes):,} bytes ({len(tflite_bytes) / 1024:.1f} KB)"
    )

    if len(tflite_bytes) <= 120 * 1024:
        print("  ✓ Within 120 KB flash target")
    else:
        print("  ✗ Exceeds 120 KB flash target — review model architecture", file=sys.stderr)

    # --- Save artifacts ---
    model_dir = args.data / "model"
    model_dir.mkdir(exist_ok=True)

    tflite_path = model_dir / "spark_cnn_int8.tflite"
    tflite_path.write_bytes(tflite_bytes)
    print(f"  Saved: {tflite_path}")

    header_content = generate_c_header(tflite_bytes)
    header_path = model_dir / "spark_cnn_int8.h"
    header_path.write_text(header_content)
    print(f"  Saved: {header_path}")

    if args.firmware_out:
        args.firmware_out.mkdir(parents=True, exist_ok=True)
        fw_header_path = args.firmware_out / "spark_cnn_int8.h"
        shutil.copy2(header_path, fw_header_path)
        print(f"  Copied to firmware: {fw_header_path}")

    # --- Evaluate FP32 vs INT8 ---
    print("Evaluating FP32 Keras model on test set...")
    keras_model = tf.keras.models.load_model(keras_path)
    fp32_metrics = evaluate_keras_model(keras_model, X_test, y_test)

    print("Evaluating INT8 TFLite model on test set...")
    int8_metrics = evaluate_tflite_model(tflite_bytes, X_test, y_test)

    # --- Get tensor info ---
    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    interpreter.allocate_tensors()
    tensor_info = get_tensor_info(interpreter)

    # --- Write report ---
    report = format_report(
        tflite_bytes=tflite_bytes,
        keras_model_path=keras_path,
        tensor_info=tensor_info,
        fp32_metrics=fp32_metrics,
        int8_metrics=int8_metrics,
        num_test_windows=len(test_idx),
        num_calibration=args.num_calibration,
    )
    report_path = model_dir / "quantization_report.txt"
    report_path.write_text(report + "\n")
    print(f"\n{report}")
    print(f"\nReport saved to {report_path}")
    print(f"All quantization artifacts written to {model_dir}")


if __name__ == "__main__":
    main()
